import Link from "next/link";
import { DanishHeader } from "../../DanishHeader";
import { DanishMalaysiaCostAndVisit } from "./DanishMalaysiaCostAndVisit";
export default function DanishMalaysiaPage(){return <main><DanishHeader/>
  <section className="malaysia-split-hero"><div className="malaysia-split-images" aria-hidden="true"><div className="malaysia-city-panel"><img src="/images/kl%20BACK%20GORUND.avif" alt=""/></div><div className="malaysia-island-panel"><img src="/images/Emerald%20bay%20pkl.jpg" alt=""/></div></div><div className="malaysia-split-shade"/><div className="site-shell malaysia-split-copy"><p className="eyebrow light">Malaysia · Storby og livsstil</p><h1>Fra international storby til smukke strande og øer.</h1><p className="malaysia-split-line">Malaysia har mere at byde på.</p><p className="malaysia-split-intro">Kuala Lumpur kombinerer international virksomhed, ejendomme og forbindelser med tropiske øer, kystliv og en enestående livskvalitet.</p><div className="malaysia-split-actions"><Link className="button button-gold" href="/da/enquire">Udforsk Malaysia <span>→</span></Link><a className="text-link light-link" href="#malaysia-opportunities-da">Se ejendomsmuligheder <span>→</span></a></div></div></section>
  <section className="market-landing-intro section-pad"><div className="site-shell narrow-grid"><p className="eyebrow">Et alternativ til Dubai</p><div><h2>Sammenlign ophold, virksomhed og livsstil.</h2><p>Malaysia kan for skandinaviske iværksættere og familier tilbyde en anden kombination af omkostninger, virksomhed, ophold, ejendom og livskvalitet end Dubai. Vi koordinerer en reel sammenligning gennem lokale specialister.</p></div></div></section>
  <section className="china-contact section-pad"><div className="site-shell china-contact-grid"><div><p className="eyebrow">Ophold og selskabsstiftelse</p><h2>Skab en base<br/>i Malaysia.</h2></div><div><p>Vi koordinerer Labuan-selskabsstiftelse, arbejdstilladelse og ophold for afhængige familiemedlemmer med en etableret lokal selskabs- og rådgivningsspecialist.</p><div className="channel-tags"><span>Labuan-selskab</span><span>Arbejdstilladelse</span><span>Familieophold</span></div><Link className="button button-dark" href="/da/services/labuan-company-residency">Se Labuan-løsningen <span>→</span></Link></div></div></section>
  <section className="malaysia-services section-pad"><div className="site-shell"><p className="eyebrow light">Sådan forbinder vi markederne</p><div className="area-feature-grid"><article><span>01</span><h2>Private kunder</h2><p>Ejendom, ophold og relocation bygget omkring familiens og virksomhedens langsigtede planer.</p></article><article><span>02</span><h2>Professionelle partnere</h2><p>Direkte samarbejde med etablerede ejendoms-, selskabs- og rådgivningsspecialister i Malaysia.</p></article><article><span>03</span><h2>Koordinering på tværs af grænser</h2><p>Én kontaktperson til ejendom, jura, skat, virksomhed og relocation.</p></article></div></div></section>
  <section className="kl-opportunities section-pad" id="malaysia-opportunities-da"><div className="site-shell"><div className="kl-heading"><div><p className="eyebrow">Ejendomme i Kuala Lumpur</p><h2>Udvalgte muligheder.<br/>Direkte lokal adgang.</h2></div><div><p>Adgang til udvalgte nybyggerier i Kuala Lumpur med muligheder i den bredere portefølje fra cirka <strong>US$150.000</strong>.</p><Link className="text-link" href="/da/enquire">Anmod om aktuelle muligheder <span>→</span></Link></div></div><article className="kl-feature"><div className="kl-feature-image"><img src="/images/kl-armani-skyline.webp" alt="Armani Hallson KLCC i Kuala Lumpurs skyline"/><span>Kunstnerisk visualisering</span></div><div className="kl-feature-copy"><p className="eyebrow">Udvalgt projekt</p><h3>Armani Hallson KLCC</h3><p>Et freehold-projekt på Jalan Ampang, cirka 300 meter fra KLCC, med panoramaudsigt, fleksible SOHO- og SOVO-planløsninger og eksklusive faciliteter.</p><ul><li>Central beliggenhed ved KLCC</li><li>Freehold-ejerskab</li><li>Planløsninger fra 406 til 1.182 sq ft</li><li>Pool, fitness, sky lounge og udsigtsdæk</li><li>Planlagt færdiggørelse i 2029</li></ul></div></article><div className="kl-gallery"><figure><img src="/images/kl-armani-arrival.webp" alt="Ankomst"/><figcaption><span>01</span>Ankomst</figcaption></figure><figure><img src="/images/kl-armani-rooftop.webp" alt="Tagfaciliteter"/><figcaption><span>02</span>Tagfaciliteter</figcaption></figure><figure><img src="/images/kl-armani-pool.webp" alt="Pool med KLCC-udsigt"/><figcaption><span>03</span>Pooldæk</figcaption></figure><figure><img src="/images/kl-armani-gym.webp" alt="Sky gym"/><figcaption><span>04</span>Sky gym</figcaption></figure></div><p className="kl-image-note">Alle projektbilleder er kunstneriske visualiseringer til markedsføringsbrug.</p></div></section>
  <DanishMalaysiaCostAndVisit/><footer className="zh-footer"><div className="site-shell"><Link className="brand" href="/da"><span className="brand-lockup"><img className="brand-symbol" src="/images/pf-gold-symbol.png" alt=""/><span className="brand-words"><b>Property</b><b>Facilitators</b></span><span className="brand-region">EuroAsia</span></span></Link><p>Ejendom, ophold og virksomhed mellem Europa og Malaysia.</p><Link className="language-link" href="/markets/malaysia">English version →</Link></div></footer>
</main>}
