import Link from "next/link";
import { PartnerStrip } from "../../components/PartnerStrip";

export default function ChineseMadronalPage() {
  return <main className="zh-site zh-zagaleta-page" lang="zh-CN">
    <header className="zh-area-header"><div className="site-shell zh-header-inner"><Link className="brand" href="/zh"><span className="brand-lockup" aria-hidden="true"><img className="brand-symbol" src="/images/pf-gold-symbol.png" alt=""/><span className="brand-words"><b>Property</b><b>Facilitators</b></span><span className="brand-region">EuroAsia</span></span></Link><nav><Link href="/zh">中文首页</Link><a href="#life-cn">生活方式</a><a href="#homes-cn">住宅类型</a><Link className="language-link" href="/areas/el-madronal">EN</Link></nav></div></header>

    <section className="zh-zag-hero zh-madronal-hero"><div className="area-overlay"/><div className="site-shell zh-zag-hero-copy"><p className="eyebrow light">Benahavís · Marbella Hills</p><h1>El Madroñal</h1><p>坐落于自然山林之间，兼顾私密、景观与日常便利的成熟高端住宅社区。</p><a className="button button-gold" href="#explore-cn">深入了解 <span>↓</span></a></div></section>

    <section className="zh-zag-intro section-pad" id="explore-cn"><div className="site-shell zh-split"><p className="eyebrow">真实的 El Madroñal</p><div><h2>居于山林，<em>仍与 Marbella 保持恰到好处的距离。</em></h2><p>El Madroñal 是一个有门禁管理的成熟山地别墅社区。蜿蜒安静的道路、成熟植被、开阔海景与各具个性的私人住宅，塑造出低调而自然的生活氛围。</p></div></div></section>

    <section className="zh-zag-numbers section-pad"><div className="site-shell"><div className="zh-section-heading"><div><p className="eyebrow light">位置与日常</p><h2>私密，但并不与生活脱节。</h2></div><p>社区靠近 San Pedro 与 Marbella，适合希望长期居住、同时重视安全与自然环境的国际家庭。</p></div><div className="zh-number-grid"><article><strong>约15分钟</strong><span>前往 Puerto Banús</span></article><article><strong>约20分钟</strong><span>前往 Marbella 市区</span></article><article><strong>24小时</strong><span>门禁与安保管理</span></article><article><strong>全年</strong><span>成熟住宅社区</span></article></div></div></section>

    <section className="zh-zag-life section-pad" id="life-cn"><div className="site-shell zagaleta-life-grid"><div><p className="eyebrow">生活方式</p><h2>在家享受宁静，<em>需要时轻松连接海岸生活。</em></h2></div><div className="zagaleta-life-list"><article><span>自然环境</span><p>成熟树木、山地地形与安静道路为住宅带来距离感、隐私与独特景观。</p></article><article><span>家庭生活</span><p>国际学校、海滩、高尔夫、餐厅与购物设施均在合理车程内，适合家庭及长期居住。</p></article><article><span>景观</span><p>许多别墅拥有地中海与山景；部分高处地块可远眺 Gibraltar 及非洲海岸线。</p></article><article className="honest-note"><span>社区个性</span><p>这里的魅力并非度假村式配套，而是自然、住宅个性、便利性与低调私密之间的平衡。</p></article></div></div></section>

    <section className="zagaleta-gallery madronal-gallery section-pad" aria-labelledby="madronal-gallery-title-cn"><div className="site-shell"><div className="zagaleta-gallery-heading"><p className="eyebrow">走进 El Madroñal</p><h2 id="madronal-gallery-title-cn">自然之间的经典优雅。</h2></div><div className="zagaleta-gallery-grid"><figure><img src="/images/madronal-overview.webp" alt="El Madroñal 经典庄园与地中海海岸全景"/><figcaption><span>01</span>El Madroñal 全景</figcaption></figure><figure><img src="/images/madronal-classic-detail.webp" alt="El Madroñal 别墅的传统露台与成熟花园"/><figcaption><span>02</span>经典风格</figcaption></figure><figure><img src="/images/madronal-classic-villa.webp" alt="带私人泳池和成熟花园的 El Madroñal 经典别墅"/><figcaption><span>03</span>经典雅致</figcaption></figure><figure><img src="/images/madronal-nature.webp" alt="El Madroñal 庄园内的林间小径与成熟松林"/><figcaption><span>04</span>融于自然</figcaption></figure></div></div></section>

    <section className="zh-zag-property section-pad" id="homes-cn"><div className="site-shell"><div className="zh-section-heading"><div><p className="eyebrow">住宅与建筑</p><h2>每一栋住宅，<br/>都有自己的表达。</h2></div><p>El Madroñal 并没有统一的建筑模板。地块高低、朝向、道路条件、周边环境与景观都会直接影响居住体验和长期价值。</p></div><div className="property-band-list"><article><span>安达卢西亚风格</span><div><h3>传统庄园别墅</h3><p>庭院、成熟花园与宽阔露台构成鲜明地域特色，部分住宅亦具备优质翻新潜力。</p></div></article><article><span>地中海风格</span><div><h3>家庭型私人庄园</h3><p>围绕泳池、花园与户外生活设计，并为家庭成员、宾客及工作人员提供灵活空间。</p></div></article><article><span>当代风格</span><div><h3>现代设计住宅</h3><p>利用山地地形获得开阔景观、自然采光、大面积玻璃与流畅的室内外连接。</p></div></article></div></div></section>

    <section className="zh-zag-security section-pad"><div className="site-shell zagaleta-practical-grid"><div><p className="eyebrow light">私密与便利</p><h2>适合长期生活的成熟选择。</h2><p>门禁入口与安全管理保障低调生活，而地理位置又让学校、海岸设施与 Marbella 社交生活保持便捷可达。</p></div><div><h3>核心吸引力</h3><ul><li>安全门禁住宅环境</li><li>地中海与山地全景</li><li>大型私人别墅与花园</li><li>多样化建筑风格</li><li>便捷连接 Marbella 与 San Pedro</li><li>适合家庭及全年居住</li></ul></div></div><div className="site-shell source-note">社区信息根据 <a href="https://luxoestates.com/lifestyle/la-zagaleta-vs-el-madronal-which-is-the-best-luxury-residential-community-in-marbella/" target="_blank" rel="noreferrer">Luxo Estates 社区指南</a>整理。车程仅供参考，具体物业状况与供应需单独核实。</div></section>

    <section className="mini-cta"><div className="site-shell"><p className="eyebrow light">私人置业咨询</p><h2>让我们为您开启正确的大门。</h2><Link className="button button-gold" href="/zh#contact-zh">联系中国与亚洲团队 <span>→</span></Link></div></section>
    <PartnerStrip />
    <footer className="zh-footer"><div className="site-shell"><Link className="brand" href="/zh"><span className="brand-lockup" aria-hidden="true"><img className="brand-symbol" src="/images/pf-gold-symbol.png" alt=""/><span className="brand-words"><b>Property</b><b>Facilitators</b></span><span className="brand-region">EuroAsia</span></span></Link><p>连接西班牙与亚洲的独立私人豪宅顾问。</p><Link className="language-link" href="/areas/el-madronal">English version →</Link></div></footer>
  </main>;
}
