import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { DanishHeader } from "../../DanishHeader";
import styles from "../../../services/labuan-company-residency/Labuan.module.css";

export const metadata:Metadata={title:"Labuan-selskab og ophold i Malaysia",description:"En koordineret vej til Labuan-selskabsstiftelse, malaysisk arbejdstilladelse og familieophold gennem lokale specialister."};
const formation=[["Navnesøgning og reservation","US$202,50"],["Stiftelse og LFSA-registrering","US$2.430"],["Lovpligtige dokumenter og selskabspakke","US$472,50"],["Registreret kontor og lokal secretary – første år","US$2.025"],["Regulatorisk registrering og compliance-opsætning","US$945"]];
const residency=[["Employment Pass – hovedansøger","US$3.577,50"],["Immigrationsregistrering og godkendelsesgebyrer","US$2.025"],["Ophold for afhængig eller associate","US$1.822,50"]];

export default function DanishLabuanPage(){return <main className={styles.page}><DanishHeader/>
  <section className={styles.hero}><Image src="/images/kl%20BACK%20GORUND.avif" alt="Kuala Lumpurs skyline" fill priority sizes="100vw" className={styles.heroImage}/><div className={styles.heroShade}/><div className={`site-shell ${styles.heroCopy}`}><p className="eyebrow light">Malaysia · Labuan IBFC</p><h1>En selskabsstruktur.<br/>En vej til ophold.</h1><p>Én koordineret løsning for internationale iværksættere og familier – fra Labuan-selskab og compliance til arbejdstilladelse og ophold for afhængige familiemedlemmer.</p><div className={styles.heroActions}><Link className="button button-gold" href="/da/enquire">Anmod om en privat vurdering <span>→</span></Link><a className="text-link light-link" href="#package-da">Se pakken <span>↓</span></a></div></div></section>
  <section className={styles.intro}><div className={`site-shell ${styles.introGrid}`}><div><p className="eyebrow">Hvorfor Labuan?</p><h2>Internationalt orienteret.<br/>Praktisk koordineret.</h2></div><div className={styles.leadCopy}><p>Labuan er Malaysias internationale virksomheds- og finanscenter. For den rette kunde og aktivitet kan et Labuan-selskab kombinere en effektiv selskabsramme med adgang til en malaysisk arbejdstilladelsesordning.</p><p>Property Facilitators EuroAsia koordinerer processen med en etableret specialist i Labuan og giver én klar kontaktperson fra egnethedsvurdering til dokumentation og registrering.</p></div></div></section>
  <section className={styles.highlights}><div className="site-shell"><div className={styles.highlightGrid}><article><span>01</span><strong>Op til fire direktører</strong><p>Et selskab kan understøtte ansøgninger for kvalificerede direktør- eller seniorroller, afhængigt af godkendelse og reelt driftsbehov.</p></article><article><span>02</span><strong>Familien kan medtages</strong><p>Ansøgninger for kvalificerede nære familiemedlemmer kan koordineres sammen med hovedansøgeren.</p></article><article><span>03</span><strong>Vedvarende ordning</strong><p>Arbejdstilladelser udstedes normalt for en periode og kan fornyes ved fortsat overholdelse og myndighedsgodkendelse.</p></article><article><span>04</span><strong>Start på afstand</strong><p>Selskabsstiftelse og indledende bankintroduktioner kan begynde online. Banken kan senere kræve personligt fremmøde.</p></article></div></div></section>
  <section className={styles.taxSection}><div className={`site-shell ${styles.taxGrid}`}><div className={styles.taxImageWrap}><Image src="/images/Emerald%20bay%20pkl.jpg" alt="Kystlandskab i Malaysia" fill sizes="(max-width:800px) 100vw,48vw" className={styles.taxImage}/></div><div className={styles.taxCopy}><p className="eyebrow light">Skatteramme</p><h2>Potentielt effektiv.<br/>Altid afhængig af fakta.</h2><div className={styles.taxCards}><article><strong>3%</strong><p>Kvalificeret handelsaktivitet i Labuan kan beskattes med 3 % af revideret nettooverskud, når substans- og regulatoriske krav er opfyldt.</p></article><article><strong>0%</strong><p>Kvalificeret ikke-handelsmæssig investerings- og holdingaktivitet kan være fritaget for Labuan business activity tax, når kravene er opfyldt.</p></article></div><p className={styles.caution}>Klassifikationen afhænger af selskabets faktiske aktivitet, indkomst og substans. Manglende overholdelse kan medføre malaysisk skat på 24 %. Uafhængig skatterådgivning er nødvendig.</p></div></div></section>
  <section className={styles.requirements}><div className={`site-shell ${styles.requirementGrid}`}><div><p className="eyebrow">Grundlæggende krav</p><h2>Til reel virksomhedsaktivitet.</h2></div><div className={styles.requirementList}><article><span>RM10.000+</span><div><h3>Minimum månedlig indkomst</h3><p>Aktuel LFSA-vejledning angiver mindst RM10.000 om måneden eller tilsvarende udenlandsk valuta for en ansøger.</p></div></article><article><span>KYC</span><div><h3>Professionel og økonomisk baggrund</h3><p>Forvent krav om pas, CV, referencer, rolle, erfaring og fit-and-proper-kontrol.</p></div></article><article><span>Substans</span><div><h3>Aktivitetsbaseret compliance</h3><p>Krav til medarbejdere, årlige udgifter, kontor, ledelse og journalføring varierer efter aktivitet.</p></div></article><article><span>Fornyelse</span><div><h3>Løbende dokumentation</h3><p>Fornyelser kræver fortsat overholdelse og dokumentation såsom lønsedler, bankudtog og årlige indkomstoplysninger.</p></div></article></div></div></section>
  <section className={styles.package} id="package-da"><div className="site-shell"><div className={styles.packageHeading}><div><p className="eyebrow light">Vejledende professionel pakke</p><h2>Fra stiftelse til ophold.</h2></div><div><strong>US$13.500</strong><span>Samlet for det beskrevne omfang</span></div></div><div className={styles.priceColumns}><article><header><div><span>Fase 1</span><h3>Selskabsstiftelse</h3></div><strong>US$6.075</strong></header><ul>{formation.map(([label,price])=><li key={label}><span>{label}</span><b>{price}</b></li>)}</ul></article><article><header><div><span>Fase 2</span><h3>Visum og ophold</h3></div><strong>US$7.425</strong></header><ul>{residency.map(([label,price])=><li key={label}><span>{label}</span><b>{price}</b></li>)}</ul></article></div><div className={styles.packageNotes}><p><strong>Forventet tid:</strong> cirka 3–4 uger fra komplette dokumenter til selskabsstiftelse og LFSA-godkendelse; immigrationstiden kan variere.</p><p><strong>Løbende administration:</strong> budget fra cirka US$4.050 om året afhængigt af aktivitet, compliance, regnskab, revision, licens og substans.</p><p><strong>Omfang:</strong> Prisen omfatter én hovedansøger og én afhængig eller associate som beskrevet. Yderligere ansøgere og ydelser prissættes særskilt.</p></div></div></section>
  <section className={styles.process}><div className="site-shell"><div className={styles.processHeading}><p className="eyebrow">Processen</p><h2>Fire klare faser.</h2></div><ol><li><span>Uge 1</span><div><h3>Egnethed, KYC og navnegodkendelse</h3><p>Aktivitet, ansøgerprofil og familiebehov afklares før dokumenter og selskabsnavn indsendes.</p></div></li><li><span>Uge 2</span><div><h3>Stiftelsesdokumenter</h3><p>Selskabs- og støttedokumentation udarbejdes til Labuan-ansøgningen.</p></div></li><li><span>Uge 3</span><div><h3>LFSA-gennemgang</h3><p>Regulatoriske spørgsmål håndteres, mens opholdsdokumenterne forberedes parallelt.</p></div></li><li><span>Uge 4</span><div><h3>Godkendelse og immigration</h3><p>Efter stiftelse og licensgodkendelse går ansøgningerne videre til de relevante myndigheder.</p></div></li></ol></div></section>
  <section className={styles.cta}><div className={`site-shell ${styles.ctaGrid}`}><div><p className="eyebrow light">Privat vurdering</p><h2>Er Labuan den rigtige løsning?</h2></div><div><p>Fortæl om den planlagte virksomhed, nuværende skattemæssige hjemsted, familiebehov og tidsplan. Vi koordinerer en indledende egnethedsvurdering før nogen forpligtelse.</p><Link className="button button-gold" href="/da/enquire">Drøft din struktur <span>→</span></Link></div></div></section>
  <section className={styles.disclaimer}><div className="site-shell"><p>Denne side er generel information og ikke juridisk, skattemæssig eller immigrationsmæssig rådgivning. Skat, arbejdstilladelse, familieophold, bank og tidsplan afhænger af gældende regler, godkendelse og individuelle forhold. Intet resultat kan garanteres.</p></div></section><footer className="zh-footer"><div className="site-shell"><Link className="brand" href="/da"><span className="brand-lockup"><img className="brand-symbol" src="/images/pf-gold-symbol.png" alt=""/><span className="brand-words"><b>Property</b><b>Facilitators</b></span><span className="brand-region">EuroAsia</span></span></Link><p>Labuan-selskab og ophold i Malaysia.</p><Link className="language-link" href="/services/labuan-company-residency">English version →</Link></div></footer>
</main>}
