import Link from "next/link";
import styles from "../HomeRegions.module.css";
import { DanishHeader } from "./DanishHeader";

const services = [
  ["01", "Købsrådgivning", "Strategisk ejendomskøb for private kunder, family offices og investorer – både offentligt markedsførte og diskrete off-market muligheder.", "/da/services/acquisition"],
  ["02", "Internationalt salg", "Præsentation af særlige ejendomme i Spanien, Mellemøsten og Malaysia for kvalificerede internationale købere gennem betroede netværk.", "/da/services/international-sales"],
  ["03", "Relocation og ophold", "Koordinering af relocation, opholdsordninger, visum, selskabsstiftelse og ejerstrukturer gennem vores juridiske samarbejdspartnere.", "/da/services/relocation-concierge"],
  ["04", "Concierge og luksusudlejning", "Eksklusive villaophold i Sydspanien samt adgang til privatfly, luksusbiler, yachtcharter, sikkerhed og skræddersyede services.", "/da/luxury-villa-rentals"],
];

export default function DanishHome() {
  return <main>
    <DanishHeader />

    <section className="hero"><div className="hero-shade"/><div className="hero-grid site-shell"><div className="hero-copy reveal-up"><p className="eyebrow light">Europa og Asien forbundet</p><h1>Din indgang til <span>internationale muligheder.</span></h1><p className="hero-intro">Ejendom · Relocation · Ophold · Virksomhedsudvidelse</p><p className="hero-intro">Vi hjælper investorer, iværksættere, familier og internationalt mobile fagfolk med at skabe nye muligheder i Europa og Asien gennem et betroet netværk af erfarne lokale partnere.</p><p className="hero-intro">Fra luksusejendomme i Spanien til virksomheds- og opholdsmuligheder i Malaysia, Hongkong, Singapore og videre – vi gør international investering, relocation og ekspansion overskuelig og professionelt understøttet.</p><div className="hero-actions"><a className="button button-gold" href="#markets-da">Se mulighederne <span>→</span></a><Link className="text-link light-link" href="/enquire">Book en fortrolig samtale <span>→</span></Link></div></div><aside className="hero-note"><span className="gold-rule"/><p>Betroet netværk i Europa og Asien</p><small>Spanien · Malaysia · Hongkong · Singapore<br/>UAE · Thailand</small></aside></div><div className="hero-footer site-shell"><p>Ejendom · Relocation · Ophold · Virksomhedsudvidelse</p><p className="scroll-note">Rul ned og oplev mere</p></div></section>

    <section className={styles.regionsSection} id="markets-da"><div className="site-shell"><div className={styles.heading}><div><p className="eyebrow">Ejendomme i Spanien</p><h2>Marbella og Benahavís.<em>Costa del Sol.</em></h2></div><p>Få adgang til vores etablerede ejendomsservice i Spanien, herunder Marbella, La Zagaleta, El Madroñal, private landejendomme og eksklusive villaophold.</p></div><div className={styles.regionGrid}><article className={`${styles.regionCard} ${styles.spain}`}><div className={styles.regionInner}><span className={styles.regionLabel}>Spanien · Costa del Sol</span><div className={styles.regionCopy}><h3>Spanien</h3><p>Luksusboliger, private ejendomme og relocation i Marbella, Benahavís og på Costa del Sol.</p><nav className={styles.subLinks}><Link href="/da/markets/marbella">Marbella</Link><Link href="/da/areas/la-zagaleta">La Zagaleta</Link><Link href="/da/areas/el-madronal">El Madroñal</Link><Link href="/da/private-portfolio">Private ejendomme</Link></nav></div><Link className={styles.cardCta} href="/da/markets/marbella">Se ejendomme i Spanien →</Link></div></article></div></div></section>

    <section className="services-section section-pad" id="services-da"><div className="site-shell"><div className="section-heading-row"><div><p className="eyebrow light">Det tilbyder vi</p><h2>Personlig service.<br/>Internationalt perspektiv.</h2></div><p>Én betroet kontaktperson til køb, salg, relocation og særlige ophold på tværs af landegrænser.</p></div><div className="service-list">{services.map(([number,title,text,href]) => <Link className="service-row" href={href} key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{text}</p><span className="round-arrow">→</span></Link>)}</div></div></section>

    <section className="gateway-section"><div className="gateway-image" role="img" aria-label="Eksklusiv bolig i en asiatisk storby"/><div className="gateway-copy"><p className="eyebrow light">Europa møder Asien</p><h2>Én relation.<br/>To verdener.</h2><p>Vi hjælper skandinaviske kunder med at forstå mulighederne i både Spanien og Asien, åbner de rigtige døre og samordner ejendom, juridiske forhold, skat og relocation gennem erfarne lokale specialister.</p><div className="gateway-points"><span>Lokal tilstedeværelse</span><span>Grænseoverskridende koordinering</span><span>Fortroligt privat netværk</span></div><Link className="text-link light-link" href="/da/about">Læs om vores tilgang <span>→</span></Link></div></section>

    <section className="market-section section-pad"><div className="site-shell market-grid"><div className="market-card image-card"><div className="image-card-label"><p className="eyebrow light">Spanien</p><h3>Særlig adgang til Costa del Sol</h3></div></div><div className="market-copy"><p className="eyebrow">Lokalt markedskendskab</p><h2>Viden bygget gennem årtier – ikke databaser.</h2><p>På de bedste boligmarkeder er de stærkeste muligheder ikke altid offentligt synlige. Vores arbejde bygger på langvarige lokale relationer, direkte markedskendskab og en ærlig vurdering af værdien.</p><ul><li><span>01</span> Søgning på det åbne marked og off-market</li><li><span>02</span> Erhvervsmæssig og juridisk koordinering</li><li><span>03</span> Support gennem hele ejerforløbet</li></ul></div></div></section>

    <section className="cta-section"><div className="site-shell cta-inner"><p className="eyebrow light">En fortrolig samtale</p><h2>Fortæl os, hvad du ønsker at opnå.</h2><p>Uanset om du køber, sælger, flytter eller undersøger et strategisk samarbejde, svarer vi personligt og fortroligt.</p><Link className="button button-gold" href="/da/enquire">Start din forespørgsel <span>→</span></Link></div></section>
    <footer className="zh-footer"><div className="site-shell"><Link className="brand" href="/da"><span className="brand-lockup" aria-hidden="true"><img className="brand-symbol" src="/images/pf-gold-symbol.png" alt=""/><span className="brand-words"><b>Property</b><b>Facilitators</b></span><span className="brand-region">EuroAsia</span></span></Link><p>Uafhængig international ejendomsrådgivning mellem Europa og Asien.</p><Link className="language-link" href="/">English version →</Link></div></footer>
  </main>;
}
