import Link from "next/link";
import { notFound } from "next/navigation";
import { DanishHeader } from "../DanishHeader";
import styles from "../DanishPage.module.css";

type Card = { label: string; title: string; text: string };
type PageData = { eyebrow: string; title: string; lead: string; heading: string; intro: string; cards: Card[] };

const pages: Record<string, PageData> = {
  "about": { eyebrow:"Vores tilgang", title:"Personlig rådgivning. Ærlig dømmekraft.", lead:"Vi forbinder mennesker, markeder og betroede specialister på tværs af Europa og Asien.", heading:"Uafhængig rådgivning med ét klart formål.", intro:"Vores rolle er at forstå, hvad kunden reelt ønsker at opnå, finde de rigtige muligheder og koordinere processen diskret. Vi arbejder gennem direkte relationer frem for volumen og støtter både købere, sælgere, investorer og samarbejdspartnere.", cards:[{label:"01",title:"Adgang",text:"Relationer, der skaber reelle muligheder – ikke blot flere annoncer."},{label:"02",title:"Klarhed",text:"Direkte og kommerciel rådgivning, også når det ærlige svar er at vente."},{label:"03",title:"Diskretion",text:"Privatliv, tilbageholdenhed og omhyggelig kontrol med information."},{label:"04",title:"Koordinering",text:"Én kontaktperson, som samler ejendom, jura, skat og relocation."}]},
  "services/acquisition": { eyebrow:"Købsrådgivning", title:"Den rigtige ejendom. På de rigtige vilkår.", lead:"Strategisk søgning og købsrådgivning for private kunder, family offices og investorer.", heading:"Vi repræsenterer køberens interesser.", intro:"Fra den første markedsvurdering til forhandling og gennemførelse hjælper vi med at definere kriterier, vurdere værdi og få adgang til både offentlige og diskrete muligheder gennem lokale netværk.", cards:[{label:"01",title:"Behov og strategi",text:"Vi afklarer livsstil, økonomi, tidshorisont og ejerskabsplan."},{label:"02",title:"Søgning og adgang",text:"Vi undersøger markedet og aktiverer relevante private relationer."},{label:"03",title:"Vurdering",text:"Vi sammenholder pris, placering, stand, potentiale og risici."},{label:"04",title:"Gennemførelse",text:"Vi koordinerer forhandling, juridiske rådgivere og praktiske næste skridt."}]},
  "services/international-sales": { eyebrow:"Internationalt salg", title:"Lokal ejendom. International rækkevidde.", lead:"Målrettet præsentation af særlige ejendomme for kvalificerede købere i Europa, Mellemøsten og Asien.", heading:"Positionering frem for masseeksponering.", intro:"Vi arbejder med ejere og professionelle partnere om at præsentere ejendomme korrekt, kontrollere informationsdelingen og skabe relevante introduktioner til internationale kunder.", cards:[{label:"01",title:"Positionering",text:"Vi fastlægger målgruppe, fortælling og den rette præsentationsform."},{label:"02",title:"Materiale",text:"Klar information, stærke billeder og markedsrelevant kommunikation."},{label:"03",title:"Privat distribution",text:"Selektiv deling gennem betroede internationale netværk."},{label:"04",title:"Kvalificering",text:"Seriøse interesser kontrolleres før detaljer og adgang gives."}]},
  "services/relocation-concierge": { eyebrow:"Relocation og concierge", title:"Et nyt land. Én betroet kontakt.", lead:"Praktisk koordinering af relocation, ophold, bolig, transport og livsstil gennem erfarne lokale partnere.", heading:"Vi gør den internationale flytning overskuelig.", intro:"Hvert forløb tilpasses familien, virksomheden og destinationen. Vi samler de relevante specialister og hjælper med at holde processen struktureret fra de første undersøgelser til ankomst og etablering.", cards:[{label:"01",title:"Relocation",text:"Boligsøgning, områdevalg, skoler og praktisk etablering."},{label:"02",title:"Ophold og visum",text:"Introduktion til kvalificerede juridiske og immigrationsmæssige rådgivere."},{label:"03",title:"Virksomhed",text:"Koordinering af selskabsstiftelse, bankintroduktioner og professionelle ydelser."},{label:"04",title:"Concierge",text:"Transport, ophold, sikkerhed, biler, yacht og individuelle arrangementer."}]},
  "services/labuan-company-residency": { eyebrow:"Labuan · Malaysia", title:"Selskabsstruktur og opholdsvej i Malaysia.", lead:"En fleksibel international løsning for kvalificerede iværksættere, investorer og familier – altid underlagt godkendelse og gældende regler.", heading:"Labuan kombinerer virksomhed, skat og international mobilitet.", intro:"Et Labuan-selskab kan anvendes til godkendte handels-, service- eller investeringsaktiviteter. Kvalificerede direktører og fagpersoner kan søge arbejdstilladelse, og afhængige familiemedlemmer kan normalt koordineres samtidig.", cards:[{label:"Virksomhed",title:"Op til fire direktører",text:"Et selskab kan understøtte ansøgninger for kvalificerede roller, afhængigt af reelt driftsbehov og myndighedsgodkendelse."},{label:"Skat",title:"3 % eller 0 %",text:"Kvalificeret handel kan beskattes med 3 % af revideret nettooverskud; visse ikke-handelsmæssige holdingaktiviteter kan være omfattet af 0 %, når kravene er opfyldt."},{label:"Ophold",title:"Vedvarende ordning",text:"Arbejdstilladelser struktureres normalt for en periode og kan fornyes ved fortsat overholdelse."},{label:"Familie",title:"Afhængige kan medtages",text:"Ansøgninger for kvalificerede nære familiemedlemmer kan koordineres med hovedansøgeren."}]},
  "markets/marbella": { eyebrow:"Spanien", title:"Marbella og Costa del Sol.", lead:"International livsstil, etablerede helårssamfund og et varieret marked for eksklusive boliger.", heading:"Lokalkendskab gør forskellen.", intro:"Marbella-markedet spænder fra strandnære lejligheder og golfboliger til store private ejendomme i Benahavís. Den rette løsning afhænger af hverdagsliv, adgang, sikkerhed, udsigt og langsigtet værdi.", cards:[{label:"Marbella",title:"Golden Mile",text:"Strand, restauranter, hoteller og international prestige tæt på centrum og Puerto Banús."},{label:"Benahavís",title:"La Zagaleta",text:"Et af Europas mest private og kontrollerede boligområder."},{label:"Benahavís",title:"El Madroñal",text:"Skovklædte bjergsider, individuelle villaer og bekvem adgang til kysten."},{label:"Costa del Sol",title:"Bredere muligheder",text:"Golf, havudsigt, familieområder og diskrete private ejendomme."}]},
  "markets/malaysia": { eyebrow:"Malaysia", title:"Asiens muligheder med et stærkt internationalt fundament.", lead:"Ejendom, virksomhed og relocation i et velforbundet, engelsktalende marked i Sydøstasien.", heading:"Har du overvejet Malaysia?", intro:"Malaysia tilbyder moderne infrastruktur, konkurrencedygtige leveomkostninger og adgang til nogle af Asiens vigtigste markeder. Vi forbinder kunder med etablerede lokale ejendoms-, selskabs- og relocation-specialister.", cards:[{label:"Kuala Lumpur",title:"Bolig og investering",text:"Centrale boliger og servicerede lejligheder fra tilgængelige internationale prisniveauer."},{label:"Labuan",title:"International virksomhed",text:"Regulerede selskabsstrukturer med attraktive muligheder for kvalificerede aktiviteter."},{label:"Relocation",title:"En praktisk base",text:"Engelsk anvendes bredt, og internationale familier har adgang til stærke skoler og sundhedsydelser."},{label:"Netværk",title:"Lokal gennemførelse",text:"Betroede partnere håndterer ejendom, jura, skat og praktisk etablering."}]},
  "markets/middle-east": { eyebrow:"Mellemøsten", title:"Et marked for kapital, mobilitet og internationale forbindelser.", lead:"Ejendoms- og samarbejdsmuligheder mellem Spanien, Golfen og Asien.", heading:"Relationer på tværs af regioner.", intro:"Vi hjælper kvalificerede kunder og professionelle partnere med at vurdere internationale ejendoms- og relocationmuligheder med Spanien og Asien som centrale forbindelsespunkter.", cards:[{label:"Kunder",title:"Privat købsrådgivning",text:"Udvalgte boliger og investeringer i Spanien og Asien."},{label:"Ejere",title:"International eksponering",text:"Kontrolleret adgang til relevante købere og rådgivernetværk."},{label:"Partnere",title:"Samarbejde",text:"Tydelige introduktioner og lokalt ansvar på begge sider."},{label:"Koordinering",title:"Én forbindelse",text:"Ejendom, jura, relocation og praktisk støtte samlet."}]},
  "areas/la-zagaleta": { eyebrow:"Benahavís", title:"La Zagaleta. Privatliv i international særklasse.", lead:"Et 900 hektar stort, sikkert bjergområde med meget lav tæthed, private golfbaner og usædvanligt store ejendomme.", heading:"Et sted skabt til diskretion.", intro:"La Zagaleta passer til ejere, som ønsker natur, sikkerhed, afstand og service inden for portene. Området ligger samtidig inden for praktisk køreafstand af Marbella, Puerto Banús og Málaga lufthavn.", cards:[{label:"900 hektar",title:"Plads og natur",text:"Korkege, fyrreskov, bjergterræn og lange private veje."},{label:"Sikkerhed",title:"Kontrolleret adgang",text:"Diskret, professionel sikkerhed og stærkt beskyttet privatliv."},{label:"Livsstil",title:"Private faciliteter",text:"To golfbaner, ridesport, klubhuse, fitness, tennis og padel."},{label:"Ejendom",title:"Fra villa til landejendom",text:"Etablerede hjem, moderne boliger og internationale trofæejendomme."}]},
  "areas/el-madronal": { eyebrow:"Benahavís", title:"El Madroñal. Natur, privatliv og personlighed.", lead:"Et etableret, bevogtet villaområde i bjergene over Marbella med modne haver og vidtrækkende udsigter.", heading:"Privat uden at være isoleret.", intro:"El Madroñal kombinerer rolige veje og individuelle ejendomme med bekvem adgang til skoler, strande, golf, restauranter og Puerto Banús. Hver villa har sit eget udtryk og sin egen placering i terrænet.", cards:[{label:"Beliggenhed",title:"Tæt på kysten",text:"Omtrent 15 minutter til Puerto Banús og 20 minutter til Marbella."},{label:"Miljø",title:"Moden natur",text:"Træer, højdeforskelle og store grunde skaber afstand og privatliv."},{label:"Boliger",title:"Individuel arkitektur",text:"Andalusiske, mediterrane og moderne villaer side om side."},{label:"Hverdagsliv",title:"Helårssamfund",text:"Velegnet til både internationale familier og længere ophold."}]},
  "luxury-villa-rentals": { eyebrow:"Eksklusive ophold", title:"Luksusvillaer i Marbella og Benahavís.", lead:"Udvalgte villaer, diskret service og et ophold tilpasset dine ønsker.", heading:"Mere end en villa.", intro:"Vi hjælper med at finde den rette bolig til familieferier, længere ophold, events eller en prøveperiode før et køb. Gennem vores partnere kan vi også koordinere transport og skræddersyede conciergeydelser.", cards:[{label:"Områder",title:"De bedste beliggenheder",text:"La Zagaleta, El Madroñal, Golden Mile, Sierra Blanca og udvalgte kystområder."},{label:"Service",title:"Personlig udvælgelse",text:"Vi matcher kapacitet, stil, sikkerhed, udsigt og opholdets formål."},{label:"Concierge",title:"Praktisk koordinering",text:"Lufthavnstransport, biler, privat kok, sikkerhed og aktiviteter."},{label:"Fortrolighed",title:"Diskret håndtering",text:"Personlige detaljer og særlige behov behandles omhyggeligt."}]},
  "commercial": { eyebrow:"Erhverv og investering", title:"Diskrete internationale erhvervsmuligheder.", lead:"Udvalgte hoteller, udviklingsprojekter, jord, driftsvirksomheder og ejendomsbaserede investeringer.", heading:"Kvalificeret adgang. Kontrolleret information.", intro:"Mange erhvervsmuligheder markedsføres ikke offentligt. Vi kvalificerer interesse, koordinerer fortrolighed og skaber direkte introduktioner mellem seriøse købere, ejere og professionelle rådgivere.", cards:[{label:"01",title:"Indledende forespørgsel",text:"Fortæl os aktivtype, marked og investeringsramme."},{label:"02",title:"Kvalificering",text:"Vi vurderer relevans, beslutningskraft og informationsniveau."},{label:"03",title:"NDA og materiale",text:"Fortrolighed dokumenteres før følsomme oplysninger deles."},{label:"04",title:"Introduktion",text:"Kvalificerede parter forbindes til dialog og due diligence."}]},
  "property-owners": { eyebrow:"Til ejendomsejere", title:"Præsentér din ejendom for et internationalt netværk.", lead:"En kontrolleret vej til relevante købere uden unødvendig offentlig eksponering.", heading:"Vi starter med ejendommen – og ejerens mål.", intro:"Vi vurderer positionering, materiale, fortrolighed og den mest relevante distributionsform. Ikke alle ejendomme egner sig til samme salgsstrategi, og nogle bør deles selektivt.", cards:[{label:"01",title:"Vurdering",text:"Beliggenhed, specifikation, stand, pris og målgruppe."},{label:"02",title:"Præsentation",text:"Klar tekst, billeder og nødvendige ejendomsoplysninger."},{label:"03",title:"Synlighed",text:"Offentlig, teaser-baseret eller privat introduktion."},{label:"04",title:"Køberkontakt",text:"Interesse kvalificeres før besigtigelse og dokumentdeling."}]},
  "private-portfolio": { eyebrow:"Privat portefølje", title:"Nogle muligheder kræver en privat introduktion.", lead:"Adgang til udvalgte boliger, landejendomme og ejendomsbaserede investeringer for registrerede kunder.", heading:"Fortrolighed beskytter både køber og ejer.", intro:"Registrér dine kriterier, så vi kan forstå dit behov og dele relevante offentlige eller private muligheder. Identificerende information gives først efter passende kvalificering og eventuel godkendelse.", cards:[{label:"Bolig",title:"Private villaer",text:"Ejendomme, der ikke ønskes bredt markedsført."},{label:"Jord",title:"Landejendomme og grunde",text:"Sjældne placeringer og projekter med særlige krav."},{label:"Investering",title:"Ejendomsbaserede muligheder",text:"Udvikling, hospitality og andre selektive introduktioner."},{label:"Adgang",title:"Personlig vurdering",text:"Hver registrering gennemgås før materiale frigives."}]},
  "asia-gateway": { eyebrow:"Fra Europa til Asien", title:"Din praktiske indgang til Malaysia og Asien.", lead:"Ejendom, relocation, ophold og virksomhed gennem etablerede lokale partnere.", heading:"Undersøg mulighederne før du beslutter dig.", intro:"Vi hjælper europæiske kunder, som overvejer et nyt hjem, en virksomhedsbase eller en international struktur i Asien. Malaysia kan tilbyde en attraktiv kombination af livskvalitet, adgang og omkostningsniveau.", cards:[{label:"Oplev",title:"Introduktionsbesøg",text:"Et struktureret program med områder, ejendomme og relevante specialister."},{label:"Etabler",title:"Relocation",text:"Bolig, skoler, transport og praktiske forhold."},{label:"Udvid",title:"Virksomhed",text:"Selskabsstrukturer og lokale professionelle forbindelser."},{label:"Invester",title:"Ejendom",text:"Boliger og udviklinger i Kuala Lumpur og udvalgte områder."}]},
  "privacy": { eyebrow:"Privatliv", title:"Sådan behandler vi dine oplysninger.", lead:"Vi indsamler kun de oplysninger, der er nødvendige for at besvare forespørgsler, kvalificere adgang og levere vores ydelser.", heading:"Fortrolighed er en del af vores arbejde.", intro:"Kontaktoplysninger, ejendomskriterier og dokumenter anvendes til det formål, de er indsendt til. Oplysninger deles kun med relevante samarbejdspartnere, når det er nødvendigt og passende for din forespørgsel.", cards:[{label:"Indsamling",title:"Nødvendige oplysninger",text:"Navn, kontaktdata, forespørgsel og relevante kriterier."},{label:"Formål",title:"Personlig betjening",text:"Besvarelse, kvalificering og koordinering af den ønskede service."},{label:"Deling",title:"Relevante partnere",text:"Kun når det er nødvendigt for at levere den aftalte hjælp."},{label:"Kontakt",title:"Dine rettigheder",text:"Kontakt os for spørgsmål, rettelse eller sletning af oplysninger."}]},
  "enquire": { eyebrow:"Fortrolig forespørgsel", title:"Fortæl os, hvad du ønsker at opnå.", lead:"Køb, salg, relocation, ophold, virksomhed eller strategisk samarbejde – vi svarer personligt.", heading:"Start med en kort introduktion.", intro:"Send dit navn, dine kontaktoplysninger, det relevante marked og en kort beskrivelse af dit behov til enquiry@pfeuroasia.com. Vi vender tilbage fortroligt og aftaler det passende næste skridt.", cards:[{label:"Ejendom",title:"Køb eller salg",text:"Angiv område, ejendomstype, budget og ønsket tidshorisont."},{label:"Malaysia",title:"Ophold og virksomhed",text:"Fortæl om familie, aktivitet og den løsning, du undersøger."},{label:"Relocation",title:"Flytning og livsstil",text:"Angiv destination, tidspunkt og praktiske prioriteter."},{label:"Kontakt",title:"enquiry@pfeuroasia.com",text:"Du er også velkommen til at skrive direkte på engelsk eller dansk."}]},
};

export function generateStaticParams() { return Object.keys(pages).map((key) => ({ slug: key.split("/") })); }

export default async function DanishContentPage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const key = slug.join("/");
  const page = pages[key];
  if (!page) notFound();
  return <main><DanishHeader/><section className={styles.hero}><div className={`site-shell ${styles.heroInner}`}><p className="eyebrow light">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.lead}</p></div></section><section className={styles.body}><div className="site-shell"><div className={styles.intro}><h2>{page.heading}</h2><p>{page.intro}</p></div><div className={styles.grid}>{page.cards.map((card)=><article className={styles.card} key={card.title}><span>{card.label}</span><h3>{card.title}</h3><p>{card.text}</p></article>)}</div></div></section><section className={styles.cta}><div className="site-shell"><p className="eyebrow light">En fortrolig samtale</p><h2>Fortæl os, hvad du ønsker at opnå.</h2><Link className="button button-gold" href="/da/enquire">Kontakt os <span>→</span></Link></div></section><footer className={styles.footer}><div className={`site-shell ${styles.footerInner}`}><p>Property Facilitators EuroAsia · International ejendomsrådgivning</p><div><Link href="/da">Dansk forside</Link> · <Link href="/">English</Link> · <Link href="/da/privacy">Privatliv</Link></div></div></footer></main>;
}
