import Link from "next/link";
import { notFound } from "next/navigation";
import { createMetadata, RouteSeo, type SeoPageKey } from "../../lib/seo";
import styles from "../../da/DanishPage.module.css";
import { SpanishHeader } from "../SpanishHeader";

type Card = { label: string; title: string; text: string };
type PageData = { eyebrow: string; title: string; lead: string; heading: string; intro: string; cards: Card[] };

const pages: Record<string, PageData> = {
  about: { eyebrow: "Nuestro enfoque", title: "Asesoramiento personal. Criterio honesto.", lead: "Conectamos personas, mercados y especialistas de confianza entre Europa y Asia.", heading: "Asesoramiento independiente con un objetivo claro.", intro: "Nuestra función es entender lo que el cliente desea conseguir, identificar las oportunidades adecuadas y coordinar el proceso con discreción.", cards: [{ label: "01", title: "Acceso", text: "Relaciones que generan oportunidades reales, no simplemente más anuncios." }, { label: "02", title: "Claridad", text: "Asesoramiento directo y comercial, incluso cuando la respuesta honesta es esperar." }, { label: "03", title: "Discreción", text: "Privacidad y control cuidadoso de la información." }, { label: "04", title: "Coordinación", text: "Un contacto que conecta propiedad, derecho, fiscalidad y relocation." }] },
  "services/acquisition": { eyebrow: "Asesoramiento al comprador", title: "La propiedad adecuada. En las condiciones adecuadas.", lead: "Búsqueda estratégica y representación para clientes privados, family offices e inversores.", heading: "Representamos los intereses del comprador.", intro: "Desde la definición de criterios hasta la negociación y cierre, valoramos ubicación, calidad, precio, potencial y riesgo.", cards: [{ label: "01", title: "Estrategia", text: "Definimos estilo de vida, presupuesto, plazos y estructura de propiedad." }, { label: "02", title: "Búsqueda y acceso", text: "Investigamos el mercado y activamos relaciones privadas relevantes." }, { label: "03", title: "Valoración", text: "Comparamos precio, ubicación, estado, potencial y riesgos." }, { label: "04", title: "Ejecución", text: "Coordinamos negociación, asesores jurídicos y siguientes pasos." }] },
  "services/international-sales": { eyebrow: "Venta internacional", title: "Propiedad local. Alcance internacional.", lead: "Presentación estratégica de propiedades especiales para compradores cualificados.", heading: "Posicionamiento, no exposición masiva.", intro: "Trabajamos con propietarios y profesionales para presentar cada inmueble correctamente, controlar la información y crear introducciones relevantes.", cards: [{ label: "01", title: "Posicionamiento", text: "Definimos público, relato y formato de presentación." }, { label: "02", title: "Material", text: "Información clara, imágenes sólidas y comunicación adecuada al mercado." }, { label: "03", title: "Distribución privada", text: "Difusión selectiva mediante redes internacionales de confianza." }, { label: "04", title: "Cualificación", text: "Verificamos el interés antes de facilitar detalles y acceso." }] },
  "services/relocation-concierge": { eyebrow: "Relocation y concierge", title: "Un nuevo país. Un contacto de confianza.", lead: "Coordinación práctica de residencia, vivienda, transporte y estilo de vida.", heading: "Hacemos más claro el traslado internacional.", intro: "Cada proceso se adapta a la familia, empresa y destino, reuniendo a los especialistas adecuados desde la planificación hasta la llegada.", cards: [{ label: "01", title: "Relocation", text: "Vivienda, zonas, colegios y establecimiento práctico." }, { label: "02", title: "Residencia y visado", text: "Introducción a especialistas jurídicos y migratorios cualificados." }, { label: "03", title: "Empresa", text: "Coordinación de sociedades, banca y servicios profesionales." }, { label: "04", title: "Concierge", text: "Transporte, alojamiento, seguridad y servicios personalizados." }] },
  "services/labuan-company-residency": { eyebrow: "Labuan · Malasia", title: "Sociedad y vía de residencia en Malasia.", lead: "Una solución internacional flexible para empresarios, inversores y familias cualificados.", heading: "Labuan conecta empresa, fiscalidad y movilidad internacional.", intro: "Una sociedad de Labuan puede utilizarse para actividades comerciales, de servicios o inversión autorizadas. El proceso siempre depende de la actividad real, la documentación y la aprobación vigente.", cards: [{ label: "Empresa", title: "Estructura regulada", text: "Constitución y cumplimiento coordinados mediante especialistas locales." }, { label: "Fiscalidad", title: "3 % o 0 % en casos cualificados", text: "El tratamiento depende de la actividad, sustancia y cumplimiento aplicables." }, { label: "Residencia", title: "Employment Pass", text: "Las solicitudes dependen del puesto, la empresa y la aprobación migratoria." }, { label: "Familia", title: "Dependientes", text: "Los familiares cualificados pueden coordinarse con el solicitante principal." }] },
  "markets/marbella": { eyebrow: "España", title: "Marbella y Costa del Sol.", lead: "Estilo de vida internacional y un mercado variado de propiedades exclusivas.", heading: "El conocimiento local marca la diferencia.", intro: "Marbella abarca desde apartamentos cerca del mar hasta grandes fincas privadas en Benahavís. La solución depende de acceso, seguridad, vistas y valor a largo plazo.", cards: [{ label: "Marbella", title: "Golden Mile", text: "Playa, hoteles y prestigio internacional cerca del centro y Puerto Banús." }, { label: "Benahavís", title: "La Zagaleta", text: "Una de las comunidades residenciales más privadas de Europa." }, { label: "Benahavís", title: "El Madroñal", text: "Entorno arbolado, villas individuales y acceso cómodo a la costa." }, { label: "Costa del Sol", title: "Más opciones", text: "Golf, vistas al mar, zonas familiares y propiedades privadas." }] },
  "markets/malaysia": { eyebrow: "Malasia", title: "Oportunidades en Asia con una base internacional sólida.", lead: "Propiedad, empresa y relocation en un mercado conectado del sudeste asiático.", heading: "¿Ha considerado Malasia?", intro: "Malasia ofrece infraestructura moderna, costes competitivos y acceso a importantes mercados asiáticos. Coordinamos propiedad, sociedad, residencia y relocation con especialistas locales.", cards: [{ label: "Kuala Lumpur", title: "Vivienda e inversión", text: "Apartamentos y residencias con servicios en ubicaciones centrales." }, { label: "Labuan", title: "Empresa internacional", text: "Estructuras reguladas para actividades cualificadas." }, { label: "Relocation", title: "Una base práctica", text: "Inglés ampliamente utilizado y servicios internacionales." }, { label: "Preguntas", title: "Asesor de Malasia", text: "Pregunte en español sobre vida, viajes, propiedad, residencia y Labuan." }] },
  "markets/middle-east": { eyebrow: "Oriente Medio", title: "Capital, movilidad y conexiones internacionales.", lead: "Oportunidades entre España, el Golfo y Asia.", heading: "Relaciones entre regiones.", intro: "Ayudamos a clientes y socios cualificados a evaluar oportunidades inmobiliarias y de relocation con España y Asia como puntos de conexión.", cards: [{ label: "Clientes", title: "Compra privada", text: "Propiedades seleccionadas en España y Asia." }, { label: "Propietarios", title: "Alcance internacional", text: "Acceso controlado a compradores y redes profesionales." }, { label: "Socios", title: "Colaboración", text: "Introducciones claras y responsabilidad local." }, { label: "Coordinación", title: "Una conexión", text: "Propiedad, derecho y relocation coordinados." }] },
  "areas/la-zagaleta": { eyebrow: "Benahavís", title: "La Zagaleta. Privacidad excepcional.", lead: "Una comunidad privada de baja densidad con seguridad, golf y grandes propiedades.", heading: "Un entorno creado para la discreción.", intro: "La Zagaleta es adecuada para propietarios que buscan naturaleza, seguridad, espacio y servicios dentro de una comunidad controlada.", cards: [{ label: "Entorno", title: "Espacio y naturaleza", text: "Bosque, montaña y largas carreteras privadas." }, { label: "Seguridad", title: "Acceso controlado", text: "Seguridad profesional y privacidad protegida." }, { label: "Estilo de vida", title: "Instalaciones privadas", text: "Golf, hípica, clubes, fitness, tenis y pádel." }, { label: "Propiedad", title: "Villas y fincas", text: "Residencias clásicas, contemporáneas y grandes estates." }] },
  "areas/el-madronal": { eyebrow: "Benahavís", title: "El Madroñal. Naturaleza, privacidad y carácter.", lead: "Una comunidad consolidada de villas en las montañas sobre Marbella.", heading: "Privado sin estar aislado.", intro: "El Madroñal combina tranquilidad y propiedades individuales con buen acceso a colegios, playa, golf, restaurantes y Puerto Banús.", cards: [{ label: "Ubicación", title: "Cerca de la costa", text: "Acceso práctico a Puerto Banús y Marbella." }, { label: "Entorno", title: "Naturaleza madura", text: "Árboles y grandes parcelas crean distancia y privacidad." }, { label: "Viviendas", title: "Arquitectura individual", text: "Villas andaluzas, mediterráneas y modernas." }, { label: "Vida diaria", title: "Comunidad todo el año", text: "Adecuada para familias internacionales y estancias largas." }] },
  "luxury-villa-rentals": { eyebrow: "Estancias exclusivas", title: "Villas de lujo en Marbella y Benahavís.", lead: "Villas seleccionadas, servicio discreto y estancias adaptadas a cada cliente.", heading: "Más que una villa.", intro: "Seleccionamos la vivienda adecuada para vacaciones, estancias largas, eventos o una prueba antes de comprar, con servicios de concierge mediante socios de confianza.", cards: [{ label: "Zonas", title: "Mejores ubicaciones", text: "La Zagaleta, El Madroñal, Golden Mile, Sierra Blanca y costa." }, { label: "Servicio", title: "Selección personal", text: "Capacidad, estilo, seguridad, vistas y propósito de la estancia." }, { label: "Concierge", title: "Coordinación práctica", text: "Traslados, vehículos, chef privado, seguridad y actividades." }, { label: "Privacidad", title: "Gestión discreta", text: "Necesidades personales tratadas con cuidado." }] },
  commercial: { eyebrow: "Comercial e inversión", title: "Oportunidades internacionales discretas.", lead: "Hoteles, desarrollos, terrenos, empresas y activos inmobiliarios seleccionados.", heading: "Acceso cualificado. Información controlada.", intro: "Muchas oportunidades no se anuncian públicamente. Cualificamos el interés y conectamos compradores, propietarios y asesores serios.", cards: [{ label: "01", title: "Consulta inicial", text: "Defina activo, mercado y marco de inversión." }, { label: "02", title: "Cualificación", text: "Valoramos relevancia y capacidad de decisión." }, { label: "03", title: "NDA y material", text: "La confidencialidad se formaliza antes de compartir información sensible." }, { label: "04", title: "Introducción", text: "Conectamos a las partes para diálogo y due diligence." }] },
  "property-owners": { eyebrow: "Para propietarios", title: "Presente su propiedad a una red internacional.", lead: "Una vía controlada hacia compradores relevantes sin exposición innecesaria.", heading: "Empezamos por la propiedad y los objetivos del propietario.", intro: "Valoramos posicionamiento, material, confidencialidad y distribución. No todas las propiedades requieren la misma estrategia.", cards: [{ label: "01", title: "Valoración", text: "Analizamos ubicación, calidad, documentación y atractivo internacional." }, { label: "02", title: "Presentación", text: "Preparamos un relato claro y material adecuado." }, { label: "03", title: "Distribución", text: "Seleccionamos canales públicos o privados." }, { label: "04", title: "Negociación", text: "Coordinamos interés, visitas, ofertas y asesores." }] },
  "private-portfolio": { eyebrow: "Colección privada", title: "Propiedades off-market y oportunidades confidenciales.", lead: "Acceso para compradores cualificados, family offices y asesores profesionales.", heading: "La privacidad protege a compradores y propietarios.", intro: "Las oportunidades privadas se facilitan después de una solicitud detallada y aprobación individual.", cards: [{ label: "01", title: "Registro", text: "Facilite identidad, contacto y criterios de búsqueda." }, { label: "02", title: "Revisión", text: "Cada solicitud se evalúa individualmente." }, { label: "03", title: "Acceso", text: "Los clientes aprobados reciben acceso seguro." }, { label: "04", title: "Presentación", text: "Coordinamos información y visitas de forma discreta." }] },
  "asia-gateway": { eyebrow: "Asia Gateway", title: "¿Está considerando Dubái? Compare primero con Malasia.", lead: "Residencia, fiscalidad internacional, propiedad, relocation y empresa mediante especialistas locales.", heading: "Comprenda las opciones antes de decidir.", intro: "Malasia y Labuan pueden ofrecer una combinación distinta de costes, residencia, empresa y calidad de vida. Nuestro papel es hacer posible una comparación realista.", cards: [{ label: "01", title: "Inversión inmobiliaria", text: "Oportunidades residenciales y de desarrollo en Malasia." }, { label: "02", title: "Residencia", text: "Introducción a especialistas que explican programas y requisitos vigentes." }, { label: "03", title: "Constitución de sociedades", text: "Apoyo profesional en Malasia, Labuan y jurisdicciones seleccionadas." }, { label: "04", title: "Visita introductoria", text: "Alojamiento, zonas, propiedades y reuniones coordinadas." }] },
  privacy: { eyebrow: "Privacidad", title: "Información personal tratada con discreción.", lead: "Cómo utiliza PF EuroAsia los datos enviados a través del sitio.", heading: "Recopilamos únicamente lo necesario.", intro: "Los datos se utilizan para responder, cualificar la consulta y coordinar el servicio solicitado con socios relevantes cuando sea necesario.", cards: [{ label: "Datos", title: "Información necesaria", text: "Nombre, contacto, consulta y criterios relevantes." }, { label: "Finalidad", title: "Atención personal", text: "Respuesta, cualificación y coordinación del servicio." }, { label: "Compartir", title: "Socios relevantes", text: "Solo cuando sea necesario para prestar la ayuda acordada." }, { label: "Derechos", title: "Contacto", text: "Escriba para consultar, rectificar o solicitar la eliminación de datos." }] },
};

const seoKeys: Record<string, SeoPageKey> = {
  about: "aboutEs", "services/acquisition": "acquisitionEs", "services/international-sales": "salesEs", "services/relocation-concierge": "relocationEs", "services/labuan-company-residency": "labuanEs", "markets/marbella": "marbellaEs", "markets/malaysia": "malaysiaEs", "markets/middle-east": "middleEastEs", "areas/la-zagaleta": "zagaletaEs", "areas/el-madronal": "madronalEs", "luxury-villa-rentals": "rentalsEs", commercial: "commercialEs", "property-owners": "ownersEs", "private-portfolio": "portfolioEs", "asia-gateway": "asiaEs", privacy: "privacyEs",
};

export function generateStaticParams() {
  return Object.keys(pages).map((key) => ({ slug: key.split("/") }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const pageKey = seoKeys[slug.join("/")];
  return pageKey ? createMetadata(pageKey) : {};
}

export default async function SpanishContentPage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const key = slug.join("/");
  const page = pages[key];
  const pageKey = seoKeys[key];
  if (!page || !pageKey) notFound();

  return (
    <RouteSeo pageKey={pageKey}>
      <main>
        <SpanishHeader />
        <section className={styles.hero}><div className={`site-shell ${styles.heroInner}`}><p className="eyebrow light">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.lead}</p></div></section>
        <section className={styles.body}><div className="site-shell"><div className={styles.intro}><h2>{page.heading}</h2><p>{page.intro}</p></div><div className={styles.grid}>{page.cards.map((card) => <article className={styles.card} key={card.title}><span>{card.label}</span><h3>{card.title}</h3><p>{card.text}</p></article>)}</div></div></section>
        {key === "markets/malaysia" ? <section className={styles.cta}><div className="site-shell"><p className="eyebrow light">Pregunte en español</p><h2>Abra el Asesor de Malasia y Labuan.</h2><Link className="button button-gold" href="/es/services/labuan-company-residency/adviser">Abrir el asesor <span>→</span></Link></div></section> : null}
        <section className={styles.cta}><div className="site-shell"><p className="eyebrow light">Una conversación confidencial</p><h2>Cuéntenos qué desea conseguir.</h2><Link className="button button-gold" href="/es/enquire">Contactar <span>→</span></Link></div></section>
        <footer className={styles.footer}><div className={`site-shell ${styles.footerInner}`}><p>Property Facilitators EuroAsia · Asesoramiento inmobiliario internacional</p><div><Link href="/es">Inicio</Link> · <Link href="/">English</Link> · <Link href="/es/privacy">Privacidad</Link></div></div></footer>
      </main>
    </RouteSeo>
  );
}
