import Link from "next/link";
import { DanishHeader } from "../DanishHeader";
import regionStyles from "../../HomeRegions.module.css";
import styles from "../../asia-gateway/AsiaGateway.module.css";

const services = [
  ["01","Ejendomsinvestering","Udvalgte bolig- og udviklingsmuligheder med Kuala Lumpur og Malaysia som udgangspunkt."],
  ["02","Opholdsmuligheder","Introduktion til kvalificerede lokale specialister, der kan forklare aktuelle ordninger, krav og proces."],
  ["03","Selskabsstiftelse","Professionel hjælp til etablering og drift af virksomheder i Malaysia, Labuan og udvalgte asiatiske jurisdiktioner."],
  ["04","Relocation","Praktisk koordinering for personer, familier og internationalt mobile fagfolk, der overvejer at flytte til Asien."],
  ["05","Introduktionsbesøg","Et conciergeforløb med områdeintroduktion, ejendomsbesigtigelser og møder med relevante specialister."],
  ["06","Virksomhedsudvidelse","Betroede introduktioner for europæiske virksomheder, der undersøger nye relationer og muligheder i regionen."],
];

export default function DanishAsiaGatewayPage(){return <main><DanishHeader/>
  <section className={styles.hero}><div className={styles.heroOverlay}/><div className={`site-shell ${styles.heroInner}`}><p className="eyebrow light">Asia Gateway</p><h1>Overvejer du Dubai?<em>Sammenlign Malaysia først.</em></h1><p>Ophold, international skatteplanlægning, ejendomsinvestering, relocation og virksomhed gennem et voksende netværk af erfarne lokale specialister.</p><div className={styles.heroActions}><Link className="button button-gold" href="/da/enquire">Book en fortrolig samtale <span>→</span></Link><Link className="text-link light-link" href="/da/markets/malaysia">Se mulighederne i Malaysia <span>→</span></Link></div></div></section>
  <section className={styles.introSection}><div className={`site-shell ${styles.introGrid}`}><div><p className="eyebrow">Et alternativ til den traditionelle Dubai-løsning</p><h2>Forstå mulighederne<em>før du beslutter dig.</em></h2></div><div className={styles.introCopy}><p>Mange skandinaviske kunder ser automatisk mod Dubai, når de undersøger ophold, skat, virksomhed eller et nyt internationalt liv. Malaysia og Labuan kan i de rette tilfælde tilbyde en mere fleksibel, økonomisk og familievenlig løsning.</p><p>Vores rolle er ikke at presse én destination, men at gøre sammenligningen mulig. Vi samler ejendom, selskabsstruktur, ophold, relocation og praktiske introduktioner, så beslutningen bygger på reelle alternativer.</p></div></div></section>
  <section className={regionStyles.regionsSection}><div className="site-shell"><div className={regionStyles.heading}><div><p className="eyebrow">Sammenlign retningen</p><h2>Malaysia og Golfen.<em>Forskellige muligheder.</em></h2></div><p>Malaysia kombinerer ejendom, livsstil, ophold og virksomhed. Golfen tilbyder andre styrker. Det rigtige valg afhænger af familie, aktivitet, omkostninger og langsigtet plan.</p></div><div className={regionStyles.regionGrid}><article className={`${regionStyles.regionCard} ${regionStyles.malaysia}`}><div className={regionStyles.regionInner}><span className={regionStyles.regionLabel}>Sydøstasien</span><div className={regionStyles.regionCopy}><h3>Malaysia</h3><p>Kuala Lumpur, Labuan, ejendom, relocation, selskabsstruktur og ophold.</p><nav className={regionStyles.subLinks}><Link href="/da/markets/malaysia">Kuala Lumpur</Link><Link href="/da/markets/malaysia">Ejendomme</Link><Link href="/da/services/labuan-company-residency">Labuan</Link></nav></div><Link className={regionStyles.cardCta} href="/da/markets/malaysia">Udforsk Malaysia →</Link></div></article><article className={`${regionStyles.regionCard} ${regionStyles.middleEast}`}><div className={regionStyles.regionInner}><span className={regionStyles.regionLabel}>Golfregionen</span><div className={regionStyles.regionCopy}><h3>Dubai og Mellemøsten</h3><p>Et etableret internationalt centrum med en anden omkostningsstruktur, livsstil og virksomhedsmodel.</p><nav className={regionStyles.subLinks}><span>Dubai</span><span>UAE</span><span>Saudi-Arabien</span></nav></div><Link className={regionStyles.cardCta} href="/da/markets/middle-east">Se Mellemøsten →</Link></div></article></div></div></section>
  <section className={styles.servicesSection}><div className="site-shell"><div className={styles.sectionHeading}><div><p className="eyebrow light">Det dækker vores Asia Gateway</p><h2>Én kontaktperson.<br/>Flere specialistområder.</h2></div><p>En koordineret skandinavisk indgang til de lokale ejendoms-, selskabs-, opholds- og relocation-specialister, der er nødvendige for at træffe en informeret beslutning.</p></div><div className={styles.serviceGrid}>{services.map(([number,title,text])=><article key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className={styles.malaysiaSection}><div className={`site-shell ${styles.malaysiaGrid}`}><div className={styles.malaysiaImage} role="img" aria-label="Kuala Lumpurs skyline om aftenen"/><div className={styles.malaysiaCopy}><p className="eyebrow">Udvalgt destination</p><h2>Malaysia</h2><p>Begynd i Kuala Lumpur med internationale ejendoms- og livsstilsmuligheder, eller undersøg Labuan til specialiserede samtaler om virksomhed og ophold.</p><p className={styles.priceNote}>Udvalgte ejendomme i Kuala Lumpur er tilgængelige fra cirka <strong>US$150.000</strong>, afhængigt af aktuel tilgængelighed.</p><Link className="button button-dark" href="/da/markets/malaysia">Udforsk Malaysia <span>→</span></Link></div></div></section>
  <section className={styles.comingSoon}><div className={`site-shell ${styles.comingSoonInner}`}><div><p className="eyebrow light">Se destinationen selv</p><h2>Oplev Asien, før du beslutter dig.</h2></div><div><p>Vi kan koordinere introduktionsbesøg med overnatning, lufthavnstransport, ejendomsture og møder om ophold og selskabsstiftelse.</p><Link className="text-link light-link" href="/da/enquire">Registrér din interesse <span>→</span></Link></div></div></section>
  <footer className="zh-footer"><div className="site-shell"><Link className="brand" href="/da"><span className="brand-lockup"><img className="brand-symbol" src="/images/pf-gold-symbol.png" alt=""/><span className="brand-words"><b>Property</b><b>Facilitators</b></span><span className="brand-region">EuroAsia</span></span></Link><p>International ejendoms-, opholds- og virksomhedsrådgivning mellem Europa og Asien.</p><Link className="language-link" href="/asia-gateway">English version →</Link></div></footer>
</main>}
